name: ✨ Feature Request
description: Propose a new feature for BProgress.
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: A detailed description of the feature you are proposing.
      placeholder: |
        Feature description...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Cases
      description: Provide use cases where this feature would be beneficial.
      placeholder: |
        Use case...
  - type: input
    id: provider
    attributes:
      label: Package
      description: The package (e.g. `@lop-town/bprogress-core`) concerned by the feature
      placeholder: |
        @lop-town/bprogress-core
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us understand your feature request.
      placeholder: |
        Additional context...
